<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitfb93b6aa20bac86cf270c1b35e316be5
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'App\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'App\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/app',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitfb93b6aa20bac86cf270c1b35e316be5::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitfb93b6aa20bac86cf270c1b35e316be5::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
