<?php

/*
|--------------------------------------------------------------------------
| THIS FILE HAS BEEN AUTOMATICALLY GENERATED, DO NOT EDIT!
|--------------------------------------------------------------------------
*/

namespace App;

/**
 * Class AssetsLoader
 * @package Paragon
 * @author "eddo81 <eduardo_jonnerstig@live.com>"
 */

class AssetsLoader
{
  /** @var array */
  static $assets = [
		"js" => ["/app/assets/js/app.js"],
		"css" => []
	];

  /** @var array */
  static $environment = [
		"wp_debug" => true,
		"wp_env" => "development"
	];

  /** @var string */
  static $text_domain = "paragon";

  /**
   * Returns an associative array containing the current development mode.
   * @return array
   */
  public static function get_environment()
  {
    return self::environment;
  }

  /**
   * Returns an array of strings containing the relative URLs for all dynamically named static assets that has been generated by Webpack.
   *
   * Accepts the following parameters:  'js', 'css'
   * @param string $asset_type
   * @return array
   */
  public static function get_assets(string $asset_type)
  {
    if(!isset(self::$assets[$asset_type])) {
      throw new \Exception("Invalid argument <strong>'{$asset_type}'</strong> provided to method of class: <strong>'" . get_called_class() . "'</strong>. The following arguments are permittable: <strong> 'js', 'css'</strong>.");
    }

    return self::$assets[$asset_type];
  }
}